name: Assets
on: [push]

jobs:
    prettier:
        timeout-minutes: 10
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup Node 14.x Environment
              uses: actions/setup-node@v2
              with:
                  node-version: '18.*'

            - name: Install dependencies
              working-directory: ./
              run: npm i

            - name: Run prettier check
              working-directory: ./
              run: npm run format:check

    eslint:
        timeout-minutes: 10
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup Node 14.x Environment
              uses: actions/setup-node@v2
              with:
                  node-version: '18.*'

            - name: Install dependencies
              working-directory: ./
              run: npm i

            - name: Run lint
              working-directory: ./
              run: npm run lint:check
