name: phpcs
on: [push]

jobs:
    phpcs:
        timeout-minutes: 10
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - uses: 'ramsey/composer-install@v2'
              with:
                  ignore-cache: 'yes'

            - name: Install dependencies
              working-directory: ./
              run: composer install

            - name: PHP Code Style (phpcs)
              uses: chindit/actions-phpcs@master
              with:
                  dir: /
